window.GUIDE_DATA = {
  cityMeta: [
    { name: "上海", lat: 31.2304, lon: 121.4737 },
    { name: "杭州", lat: 30.2741, lon: 120.1551 },
    { name: "北京", lat: 39.9042, lon: 116.4074 },
    { name: "广州", lat: 23.1291, lon: 113.2644 },
    { name: "深圳", lat: 22.5431, lon: 114.0579 },
    { name: "成都", lat: 30.5728, lon: 104.0668 },
    { name: "南京", lat: 32.0603, lon: 118.7969 },
    { name: "西安", lat: 34.3416, lon: 108.9398 },
    { name: "重庆", lat: 29.563, lon: 106.5516 }
  ],
  weather: {
    上海: { day: "周六", sky: "多云", temp: 24, outdoorOk: true, text: "周六多云 24°C，适合户外", tip: "滨江和市集体感舒适，记得带一件薄外套。", source: "备用" },
    杭州: { day: "周六", sky: "小雨", temp: 21, outdoorOk: false, text: "周六小雨 21°C，建议室内或备伞", tip: "西湖沿线会湿滑，展览和剧场更稳妥。", source: "备用" },
    北京: { day: "周六", sky: "晴", temp: 26, outdoorOk: true, text: "周六晴 26°C，非常适合徒步与市集", tip: "紫外线偏强，户外记得防晒。", source: "备用" },
    广州: { day: "周六", sky: "多云", temp: 28, outdoorOk: true, text: "周六多云 28°C，户外可行", tip: "湿度高，徒步选林荫路，中午避开暴晒。", source: "备用" },
    深圳: { day: "周六", sky: "晴", temp: 29, outdoorOk: true, text: "周六晴 29°C，适合湾区散步", tip: "海边风大，薄外套比伞更有用。", source: "备用" },
    成都: { day: "周六", sky: "阴", temp: 22, outdoorOk: true, text: "周六阴 22°C，体感舒适", tip: "短时小雨常见，市集和展馆都好安排。", source: "备用" },
    南京: { day: "周六", sky: "多云", temp: 23, outdoorOk: true, text: "周六多云 23°C，适合出城徒步", tip: "紫金山早晚温差在，薄外套备一件。", source: "备用" },
    西安: { day: "周六", sky: "晴", temp: 25, outdoorOk: true, text: "周六晴 25°C，城墙和市集体感好", tip: "日照强，户外补水和防晒。", source: "备用" },
    重庆: { day: "周六", sky: "多云", temp: 27, outdoorOk: true, text: "周六多云 27°C，步道可走", tip: "山城爬坡多，把行程留出喘气时间。", source: "备用" }
  },
  activities: [
    { id: "sh-01", city: "上海", title: "西岸美术馆周末特展", category: "展览", cost: 80, duration: "2.5 小时", minPeople: 1, maxPeople: 6, meetup: "龙腾大道 2100 号西岸美术馆正门", lat: 31.1668, lon: 121.4654, indoor: true, time: "周六 13:30", vibe: "慢看", desc: "沿黄浦江的白盒子展厅，适合不想赶场、只想把一个展看完的下午。" },
    { id: "sh-02", city: "上海", title: "武康路周末手作市集", category: "市集", cost: 40, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "武康路 393 号近安福路路口", lat: 31.2106, lon: 121.4388, indoor: false, time: "周六 11:00", vibe: "闲逛", desc: "梧桐树下的摊位以插画、银饰和咖啡为主，适合边走边聊。" },
    { id: "sh-03", city: "上海", title: "上海交响乐团周末室内乐", category: "演出", cost: 180, duration: "1.5 小时", minPeople: 1, maxPeople: 4, meetup: "湖南路 105 号上海交响乐团音乐厅", lat: 31.2169, lon: 121.4448, indoor: true, time: "周六 19:30", vibe: "仪式感", desc: "夜场室内乐，时长适中，适合两三人把周末过得郑重一点。" },
    { id: "sh-04", city: "上海", title: "余山森林公园半日徒步", category: "徒步", cost: 0, duration: "4 小时", minPeople: 2, maxPeople: 10, meetup: "西佘山地铁站 2 号口", lat: 31.0963, lon: 121.1862, indoor: false, time: "周六 09:00", vibe: "出汗", desc: "上海最近的像样山路，适合想离开市区又当天往返的小队。" },
    { id: "sh-05", city: "上海", title: "PSA 当代艺术博物馆", category: "展览", cost: 60, duration: "3 小时", minPeople: 1, maxPeople: 8, meetup: "花园港路 201 号电厂烟囱下", lat: 31.1916, lon: 121.4809, indoor: true, time: "周六 14:00", vibe: "开阔", desc: "旧电厂改造的大空间，一个人或一群人都可以慢慢走完。" },
    { id: "sh-06", city: "上海", title: "思南公馆旧书与咖啡市集", category: "市集", cost: 30, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "思南路 51-53 号花园入口", lat: 31.2159, lon: 121.4636, indoor: false, time: "周六 10:30", vibe: "安静", desc: "花园里翻旧书、喝手冲，适合不想太吵的周末上午。" },
    { id: "sh-07", city: "上海", title: "静安 livehouse 独立现场", category: "演出", cost: 120, duration: "2.5 小时", minPeople: 2, maxPeople: 6, meetup: "陕西北路近南京西路 livehouse 门口", lat: 31.2305, lon: 121.4505, indoor: true, time: "周六 20:00", vibe: "热闹", desc: "本地乐队周末专场，适合想把晚上过得热闹一点的朋友。" },
    { id: "sh-08", city: "上海", title: "徐汇滨江黄昏漫步", category: "徒步", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "龙腾大道龙耀路路口滨江步道", lat: 31.1662, lon: 121.4661, indoor: false, time: "周六 16:30", vibe: "轻松", desc: "平坦步道看日落，几乎零花费，适合临时组队。" },
    { id: "sh-09", city: "上海", title: "朱家角水巷半日走逛", category: "徒步", cost: 50, duration: "5 小时", minPeople: 2, maxPeople: 8, meetup: "朱家角地铁站 1 号口", lat: 31.1112, lon: 121.0514, indoor: false, time: "周六 09:30", vibe: "短途", desc: "不出上海也能走到水乡，避开主街钻小巷会更舒服。" },
    { id: "sh-10", city: "上海", title: "外滩美术馆建筑展", category: "展览", cost: 50, duration: "1.5 小时", minPeople: 1, maxPeople: 5, meetup: "虎丘路 20 号外滩美术馆大堂", lat: 31.2394, lon: 121.4908, indoor: true, time: "周六 15:00", vibe: "短看", desc: "体量小、展线短，看完可以接着去外滩散步。" },
    { id: "hz-01", city: "杭州", title: "良渚博物院文明展", category: "展览", cost: 0, duration: "2.5 小时", minPeople: 1, maxPeople: 8, meetup: "良渚博物院南门", lat: 30.3865, lon: 119.9882, indoor: true, time: "周六 13:00", vibe: "安静", desc: "免费预约制展览，雨天也舒适。" },
    { id: "hz-02", city: "杭州", title: "西湖手作市集", category: "市集", cost: 40, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "湖滨步行街音乐喷泉附近", lat: 30.259, lon: 120.1691, indoor: false, time: "周六 11:00", vibe: "热闹", desc: "湖边摊位以陶瓷、香薰和文创为主。" },
    { id: "hz-03", city: "杭州", title: "运河大剧院周末剧场", category: "演出", cost: 160, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "运河大剧院 3 号门", lat: 30.3142, lon: 120.1418, indoor: true, time: "周六 19:30", vibe: "仪式感", desc: "小剧场话剧，座位近、台词清楚，雨天首选。" },
    { id: "hz-04", city: "杭州", title: "九溪烟树林间徒步", category: "徒步", cost: 0, duration: "3.5 小时", minPeople: 2, maxPeople: 8, meetup: "九溪公交站林海亭", lat: 30.1954, lon: 120.1213, indoor: false, time: "周六 09:00", vibe: "出汗", desc: "溪声和湿石台阶是这条线的记忆点，小雨天需防滑。" },
    { id: "hz-05", city: "杭州", title: "南宋德寿宫遗址展", category: "展览", cost: 75, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "德寿宫遗址博物馆检票口", lat: 30.2463, lon: 120.1784, indoor: true, time: "周六 14:30", vibe: "慢看", desc: "遗址和文物穿插，适合对杭州历史有一点好奇的人。" },
    { id: "hz-06", city: "杭州", title: "河坊街夜间市集", category: "市集", cost: 60, duration: "2.5 小时", minPeople: 2, maxPeople: 10, meetup: "河坊街与中山中路交叉口", lat: 30.2422, lon: 120.1711, indoor: false, time: "周六 18:00", vibe: "热闹", desc: "小吃和手作混在一起，适合把晚饭和闲逛并在一次完成。" },
    { id: "hz-07", city: "杭州", title: "西溪湿地绿道慢走", category: "徒步", cost: 80, duration: "3 小时", minPeople: 1, maxPeople: 8, meetup: "西溪国家湿地公园周家村入口", lat: 30.2724, lon: 120.0632, indoor: false, time: "周六 09:30", vibe: "轻松", desc: "栈道平坦，适合不想爬山但想离开马路的组合。" },
    { id: "hz-08", city: "杭州", title: "云栖竹径半日走", category: "徒步", cost: 0, duration: "3 小时", minPeople: 2, maxPeople: 8, meetup: "云栖竹径石牌坊", lat: 30.1781, lon: 120.0884, indoor: false, time: "周六 08:30", vibe: "清爽", desc: "竹林夹道，夏季也阴凉。路面有青苔，雨天请换计划。" },
    { id: "hz-09", city: "杭州", title: "茶博周末特展", category: "展览", cost: 30, duration: "1.5 小时", minPeople: 1, maxPeople: 6, meetup: "中国茶叶博物馆双峰馆区", lat: 30.2148, lon: 120.0982, indoor: true, time: "周六 15:00", vibe: "短看", desc: "看完可以在茶室坐一会，适合想把周末过得慢一点的两三人。" },
    { id: "hz-10", city: "杭州", title: "大麦·杭州大剧院交响夜", category: "演出", cost: 220, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "杭州大剧院歌剧院入口", lat: 30.2416, lon: 120.2093, indoor: true, time: "周六 19:30", vibe: "郑重", desc: "正厅观演体验完整，适合预算更宽的组合。" },
    { id: "bj-01", city: "北京", title: "国家博物馆周末特展", category: "展览", cost: 0, duration: "3 小时", minPeople: 1, maxPeople: 6, meetup: "国家博物馆西门安检口", lat: 39.9053, lon: 116.4014, indoor: true, time: "周六 13:00", vibe: "认真", desc: "预约免费，展线很长。建议只选一个特展。" },
    { id: "bj-02", city: "北京", title: "798 周末创意市集", category: "市集", cost: 50, duration: "3 小时", minPeople: 1, maxPeople: 8, meetup: "798 艺术区 2 号门", lat: 39.9842, lon: 116.4956, indoor: false, time: "周六 11:00", vibe: "闲逛", desc: "厂区里摊位和展览混着走，适合边拍照边找午饭。" },
    { id: "bj-03", city: "北京", title: "国图艺术中心室内乐", category: "演出", cost: 150, duration: "1.5 小时", minPeople: 1, maxPeople: 4, meetup: "国家图书馆艺术中心售票厅", lat: 39.9431, lon: 116.3252, indoor: true, time: "周六 19:30", vibe: "安静", desc: "厅不大、声音近，适合不想跑到大剧院又想听现场的人。" },
    { id: "bj-04", city: "北京", title: "奥林匹克森林公园南园徒步", category: "徒步", cost: 0, duration: "3 小时", minPeople: 1, maxPeople: 10, meetup: "奥森南园南门", lat: 40.0074, lon: 116.3961, indoor: false, time: "周六 08:30", vibe: "出汗", desc: "环湖加仰山，坡度温和，适合想在城里把腿走开的周末。" },
    { id: "bj-05", city: "北京", title: "今日美术馆当代展", category: "展览", cost: 60, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "今日美术馆 1 号馆前台", lat: 39.9122, lon: 116.4435, indoor: true, time: "周六 14:00", vibe: "短看", desc: "体量适中，看完可以去附近吃一顿。" },
    { id: "bj-06", city: "北京", title: "五道营周末市集", category: "市集", cost: 40, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "五道营胡同西口", lat: 39.9413, lon: 116.4078, indoor: false, time: "周六 12:00", vibe: "轻松", desc: "胡同尺度的摊位，适合人数不多、想聊天多于购物的组合。" },
    { id: "bj-07", city: "北京", title: "三里屯周末 livehouse", category: "演出", cost: 130, duration: "2.5 小时", minPeople: 2, maxPeople: 6, meetup: "工体北路 livehouse 门口", lat: 39.9334, lon: 116.4472, indoor: true, time: "周六 20:30", vibe: "热闹", desc: "夜场站票，适合想把周六晚上交给音乐的朋友。" },
    { id: "bj-08", city: "北京", title: "香山公园半日轻徒步", category: "徒步", cost: 10, duration: "4 小时", minPeople: 2, maxPeople: 8, meetup: "香山公园东门", lat: 39.9964, lon: 116.1935, indoor: false, time: "周六 08:00", vibe: "出汗", desc: "城里最经典的爬升之一。晴天视野好，记得防晒。" },
    { id: "bj-09", city: "北京", title: "中轴线漫步：天安门到正阳门", category: "徒步", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "天安门东地铁站 C 口", lat: 39.9087, lon: 116.404, indoor: false, time: "周六 16:00", vibe: "城市", desc: "短、平、好集合，适合第一次组队。" },
    { id: "bj-10", city: "北京", title: "园博园花田与展馆", category: "展览", cost: 0, duration: "3.5 小时", minPeople: 2, maxPeople: 10, meetup: "园博园东门", lat: 39.786, lon: 116.1912, indoor: false, time: "周六 10:00", vibe: "开阔", desc: "户外观展和散步各占一半，雨天建议改室内。" },
    { id: "gz-01", city: "广州", title: "广东美术馆白鹅潭新馆", category: "展览", cost: 0, duration: "2.5 小时", minPeople: 1, maxPeople: 8, meetup: "白鹅潭广东美术馆正门", lat: 23.1095, lon: 113.241, indoor: true, time: "周六 13:30", vibe: "开阔", desc: "江边大馆，展线清楚，适合把一个下午交给展厅。" },
    { id: "gz-02", city: "广州", title: "永庆坊周末市集", category: "市集", cost: 40, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "恩宁路永庆坊牌坊", lat: 23.1248, lon: 113.2465, indoor: false, time: "周六 11:00", vibe: "闲逛", desc: "西关里的摊位和旧屋混在一起，适合边走边吃。" },
    { id: "gz-03", city: "广州", title: "星海音乐厅周末音乐会", category: "演出", cost: 180, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "星海音乐厅交响乐厅入口", lat: 23.1158, lon: 113.3047, indoor: true, time: "周六 20:00", vibe: "仪式感", desc: "二沙岛夜场，雨天也稳妥，适合两三人郑重过周末。" },
    { id: "gz-04", city: "广州", title: "白云山摩星岭徒步", category: "徒步", cost: 5, duration: "4 小时", minPeople: 2, maxPeople: 8, meetup: "白云山南门", lat: 23.1819, lon: 113.2975, indoor: false, time: "周六 08:00", vibe: "出汗", desc: "广州最经典的城里山路，建议早出发避开湿热。" },
    { id: "gz-05", city: "广州", title: "红专厂当代艺术走展", category: "展览", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "红专厂创意园正门", lat: 23.1132, lon: 113.368, indoor: true, time: "周六 14:00", vibe: "轻松", desc: "旧厂房展览，看完可以在园里喝咖啡。" },
    { id: "gz-06", city: "广州", title: "北京路步行街市集", category: "市集", cost: 50, duration: "2 小时", minPeople: 2, maxPeople: 10, meetup: "北京路与中山路交叉口", lat: 23.1256, lon: 113.2688, indoor: false, time: "周六 16:00", vibe: "热闹", desc: "人多、好集合，适合临时拉上宿舍的人出门。" },
    { id: "gz-07", city: "广州", title: "太古仓滨江黄昏走", category: "徒步", cost: 0, duration: "1.5 小时", minPeople: 1, maxPeople: 8, meetup: "太古仓码头 1 号仓", lat: 23.0986, lon: 113.266, indoor: false, time: "周六 17:30", vibe: "轻松", desc: "江风比山路友好，适合不想出汗的户外。" },
    { id: "gz-08", city: "广州", title: "广州大剧院周末剧场", category: "演出", cost: 200, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "广州大剧院歌剧厅入口", lat: 23.1165, lon: 113.324, indoor: true, time: "周六 19:30", vibe: "郑重", desc: "珠江新城夜场，适合预算更宽的组合。" },
    { id: "sz-01", city: "深圳", title: "海上世界文化艺术中心", category: "展览", cost: 80, duration: "2.5 小时", minPeople: 1, maxPeople: 6, meetup: "望海路海上世界文化艺术中心", lat: 22.4878, lon: 113.9156, indoor: true, time: "周六 13:00", vibe: "开阔", desc: "临海展馆，看完可以走到海边吹风。" },
    { id: "sz-02", city: "深圳", title: "南头古城周末市集", category: "市集", cost: 40, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "南头古城北城门", lat: 22.5436, lon: 113.923, indoor: false, time: "周六 11:00", vibe: "闲逛", desc: "城内摊位和咖啡馆密度高，适合慢慢逛。" },
    { id: "sz-03", city: "深圳", title: "深圳音乐厅周末场", category: "演出", cost: 160, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "深圳音乐厅大剧院入口", lat: 22.5478, lon: 114.059, indoor: true, time: "周六 20:00", vibe: "仪式感", desc: "市民中心夜场，交通方便，雨天首选。" },
    { id: "sz-04", city: "深圳", title: "梧桐山登顶轻徒步", category: "徒步", cost: 0, duration: "5 小时", minPeople: 2, maxPeople: 8, meetup: "梧桐山风景区门口", lat: 22.5833, lon: 114.213, indoor: false, time: "周六 07:30", vibe: "出汗", desc: "深圳最像样的爬升，晴天视野能看到海。" },
    { id: "sz-05", city: "深圳", title: "深圳美术馆莲花山馆", category: "展览", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "深圳美术馆售票处", lat: 22.555, lon: 114.059, indoor: true, time: "周六 14:30", vibe: "短看", desc: "体量适中，看完可以去莲花山散步。" },
    { id: "sz-06", city: "深圳", title: "蛇口价值工厂市集", category: "市集", cost: 30, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "价值工厂大烟囱下", lat: 22.479, lon: 113.926, indoor: false, time: "周六 12:00", vibe: "安静", desc: "旧厂房里的手作摊，比商业街区安静。" },
    { id: "sz-07", city: "深圳", title: "人才公园湾区漫步", category: "徒步", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 10, meetup: "人才公园南门", lat: 22.507, lon: 113.941, indoor: false, time: "周六 16:30", vibe: "轻松", desc: "平坦看海步道，适合临时组队和不想爬山的人。" },
    { id: "sz-08", city: "深圳", title: "华侨城周末 livehouse", category: "演出", cost: 120, duration: "2.5 小时", minPeople: 2, maxPeople: 6, meetup: "华侨城创意园 livehouse 门口", lat: 22.537, lon: 113.989, indoor: true, time: "周六 20:30", vibe: "热闹", desc: "本地乐队专场，适合把晚上交给音乐。" },
    { id: "cd-01", city: "成都", title: "成都博物馆周末展", category: "展览", cost: 0, duration: "2.5 小时", minPeople: 1, maxPeople: 8, meetup: "成都博物馆西门", lat: 30.661, lon: 104.063, indoor: true, time: "周六 13:00", vibe: "认真", desc: "天府广场旁，预约免费，适合雨天把展看完。" },
    { id: "cd-02", city: "成都", title: "东郊记忆周末市集", category: "市集", cost: 40, duration: "3 小时", minPeople: 1, maxPeople: 8, meetup: "东郊记忆正门", lat: 30.67, lon: 104.118, indoor: false, time: "周六 11:00", vibe: "闲逛", desc: "旧厂区摊位和演出混着走，适合拍照和找午饭。" },
    { id: "cd-03", city: "成都", title: "成都城市音乐厅", category: "演出", cost: 150, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "城市音乐厅音乐厅入口", lat: 30.659, lon: 104.063, indoor: true, time: "周六 19:30", vibe: "仪式感", desc: "厅很近、声音清楚，适合两三人的夜场。" },
    { id: "cd-04", city: "成都", title: "龙泉山半日徒步", category: "徒步", cost: 0, duration: "4 小时", minPeople: 2, maxPeople: 8, meetup: "龙泉山桃花故里停车场", lat: 30.597, lon: 104.274, indoor: false, time: "周六 08:30", vibe: "出汗", desc: "成都最近的像样爬升，阴天也舒服。" },
    { id: "cd-05", city: "成都", title: "天府艺术公园当代馆", category: "展览", cost: 60, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "成都当代美术馆前台", lat: 30.593, lon: 104.071, indoor: true, time: "周六 14:00", vibe: "开阔", desc: "新馆空间大，看完可以在公园里坐一会。" },
    { id: "cd-06", city: "成都", title: "宽窄巷子手作市集", category: "市集", cost: 50, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "宽巷子西口", lat: 30.671, lon: 104.054, indoor: false, time: "周六 12:00", vibe: "热闹", desc: "人多但好集合，适合把午饭和闲逛并在一起。" },
    { id: "cd-07", city: "成都", title: "锦江绿道夜走", category: "徒步", cost: 0, duration: "1.5 小时", minPeople: 1, maxPeople: 8, meetup: "九眼桥南桥头", lat: 30.655, lon: 104.083, indoor: false, time: "周六 18:30", vibe: "轻松", desc: "平坦沿江，适合吃完晚饭再走一段。" },
    { id: "cd-08", city: "成都", title: "四川大剧院周末剧", category: "演出", cost: 180, duration: "2.5 小时", minPeople: 1, maxPeople: 4, meetup: "四川大剧院2号门", lat: 30.661, lon: 104.065, indoor: true, time: "周六 19:30", vibe: "郑重", desc: "正厅观演，适合预算更宽、想看完整剧场的人。" },
    { id: "nj-01", city: "南京", title: "南京博物院特展", category: "展览", cost: 0, duration: "3 小时", minPeople: 1, maxPeople: 8, meetup: "南京博物院历史馆入口", lat: 32.042, lon: 118.848, indoor: true, time: "周六 13:00", vibe: "认真", desc: "预约免费，建议只选一个馆，避免走成体力赛。" },
    { id: "nj-02", city: "南京", title: "老门东周末市集", category: "市集", cost: 40, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "老门东牌坊", lat: 32.016, lon: 118.791, indoor: false, time: "周六 11:00", vibe: "闲逛", desc: "城南巷子里的摊位，适合边走边吃。" },
    { id: "nj-03", city: "南京", title: "江苏大剧院周末场", category: "演出", cost: 180, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "江苏大剧院歌剧厅入口", lat: 32.065, lon: 118.89, indoor: true, time: "周六 19:30", vibe: "仪式感", desc: "江东夜场，交通方便，雨天也舒服。" },
    { id: "nj-04", city: "南京", title: "紫金山头陀岭徒步", category: "徒步", cost: 0, duration: "3.5 小时", minPeople: 2, maxPeople: 8, meetup: "紫金山索道站附近登山口", lat: 32.07, lon: 118.848, indoor: false, time: "周六 08:00", vibe: "出汗", desc: "南京最经典的城里山，早出发人少。" },
    { id: "nj-05", city: "南京", title: "德基美术馆", category: "展览", cost: 80, duration: "1.5 小时", minPeople: 1, maxPeople: 5, meetup: "德基广场二期美术馆前台", lat: 32.045, lon: 118.791, indoor: true, time: "周六 14:30", vibe: "短看", desc: "商场里的白盒子，看完下楼就能吃饭。" },
    { id: "nj-06", city: "南京", title: "先锋书店五台山店坐一坐", category: "市集", cost: 30, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "广州路先锋书店入口", lat: 32.048, lon: 118.776, indoor: true, time: "周六 15:00", vibe: "安静", desc: "更像慢下来的室内停留，适合雨天和不想赶场的人。" },
    { id: "nj-07", city: "南京", title: "玄武湖环湖慢走", category: "徒步", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 10, meetup: "玄武湖翠洲门", lat: 32.072, lon: 118.796, indoor: false, time: "周六 16:00", vibe: "轻松", desc: "平坦好集合，适合第一次组队。" },
    { id: "nj-08", city: "南京", title: "南京人民大会堂音乐会", category: "演出", cost: 120, duration: "1.5 小时", minPeople: 1, maxPeople: 4, meetup: "人民大会堂音乐厅入口", lat: 32.046, lon: 118.79, indoor: true, time: "周六 19:30", vibe: "安静", desc: "厅不大，适合不想跑到江东又想听现场的人。" },
    { id: "xa-01", city: "西安", title: "陕西历史博物馆", category: "展览", cost: 0, duration: "3 小时", minPeople: 1, maxPeople: 6, meetup: "陕历博南门", lat: 34.227, lon: 108.958, indoor: true, time: "周六 12:30", vibe: "认真", desc: "预约免费。建议抓一条展线，不要贪多。" },
    { id: "xa-02", city: "西安", title: "永兴坊周末市集", category: "市集", cost: 50, duration: "2 小时", minPeople: 2, maxPeople: 10, meetup: "永兴坊牌楼", lat: 34.263, lon: 108.964, indoor: false, time: "周六 11:30", vibe: "热闹", desc: "把午饭和市集并在一次，适合人多的宿舍局。" },
    { id: "xa-03", city: "西安", title: "陕西大剧院周末剧", category: "演出", cost: 160, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "陕西大剧院戏剧厅", lat: 34.219, lon: 108.946, indoor: true, time: "周六 19:30", vibe: "仪式感", desc: "曲江夜场，适合给周末加一点郑重。" },
    { id: "xa-04", city: "西安", title: "翠华山轻徒步", category: "徒步", cost: 70, duration: "5 小时", minPeople: 2, maxPeople: 8, meetup: "翠华山景区售票处", lat: 33.98, lon: 109.02, indoor: false, time: "周六 08:00", vibe: "出汗", desc: "终南山东边的经典线，晴天值得，雨天改城墙。" },
    { id: "xa-05", city: "西安", title: "西安美术馆曲江馆", category: "展览", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "西安美术馆正门", lat: 34.199, lon: 108.986, indoor: true, time: "周六 14:00", vibe: "短看", desc: "体量适中，看完可以去大唐不夜城附近吃饭。" },
    { id: "xa-06", city: "西安", title: "永宁门城墙慢走", category: "徒步", cost: 54, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "永宁门登城口", lat: 34.255, lon: 108.942, indoor: false, time: "周六 16:30", vibe: "城市", desc: "短、平、好拍照，适合第一次来西安的组队。" },
    { id: "xa-07", city: "西安", title: "大唐不夜城夜逛", category: "市集", cost: 40, duration: "2 小时", minPeople: 2, maxPeople: 10, meetup: "大唐不夜城北入口", lat: 34.216, lon: 108.964, indoor: false, time: "周六 18:30", vibe: "热闹", desc: "把晚饭、夜景和闲逛并在一起。" },
    { id: "xa-08", city: "西安", title: "西安音乐厅室内乐", category: "演出", cost: 120, duration: "1.5 小时", minPeople: 1, maxPeople: 4, meetup: "西安音乐厅一层", lat: 34.219, lon: 108.946, indoor: true, time: "周六 19:30", vibe: "安静", desc: "厅不大，适合不想看大剧又想听现场的人。" },
    { id: "cq-01", city: "重庆", title: "重庆美术馆周末展", category: "展览", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "重庆美术馆入口", lat: 29.563, lon: 106.577, indoor: true, time: "周六 14:00", vibe: "短看", desc: "解放碑附近，看完可以接着走山城步道。" },
    { id: "cq-02", city: "重庆", title: "十八梯周末市集", category: "市集", cost: 40, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "十八梯入口", lat: 29.553, lon: 106.577, indoor: false, time: "周六 11:00", vibe: "闲逛", desc: "坡地里的摊位和老街混在一起，适合边走边拍。" },
    { id: "cq-03", city: "重庆", title: "重庆大剧院夜场", category: "演出", cost: 180, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "重庆大剧院歌剧厅", lat: 29.569, lon: 106.58, indoor: true, time: "周六 19:30", vibe: "仪式感", desc: "江北嘴夜场，结束后可以看江景。" },
    { id: "cq-04", city: "重庆", title: "山城步道半日走", category: "徒步", cost: 0, duration: "3 小时", minPeople: 2, maxPeople: 8, meetup: "凯旋路电梯上口", lat: 29.552, lon: 106.579, indoor: false, time: "周六 09:30", vibe: "出汗", desc: "真正的山城体验，台阶多，把节奏放慢。" },
    { id: "cq-05", city: "重庆", title: "原美术馆黄桷坪", category: "展览", cost: 60, duration: "2 小时", minPeople: 1, maxPeople: 6, meetup: "原美术馆前台", lat: 29.552, lon: 106.531, indoor: true, time: "周六 14:30", vibe: "安静", desc: "工业区里的当代馆，适合想看点不一样的人。" },
    { id: "cq-06", city: "重庆", title: "磁器口古镇市集", category: "市集", cost: 50, duration: "3 小时", minPeople: 2, maxPeople: 10, meetup: "磁器口正门", lat: 29.582, lon: 106.447, indoor: false, time: "周六 10:30", vibe: "热闹", desc: "人多，建议早到，把午饭解决在镇上。" },
    { id: "cq-07", city: "重庆", title: "南滨路江景漫步", category: "徒步", cost: 0, duration: "2 小时", minPeople: 1, maxPeople: 8, meetup: "南滨路海棠烟雨公园", lat: 29.548, lon: 106.586, indoor: false, time: "周六 17:00", vibe: "轻松", desc: "看对岸城市天际线，适合不想爬坡的户外。" },
    { id: "cq-08", city: "重庆", title: "国泰艺术中心演出", category: "演出", cost: 140, duration: "2 小时", minPeople: 1, maxPeople: 4, meetup: "国泰艺术中心剧场入口", lat: 29.563, lon: 106.577, indoor: true, time: "周六 19:30", vibe: "安静", desc: "小剧场距离近，雨天也很稳妥。" }
  ]
};

GUIDE_DATA.cities = GUIDE_DATA.cityMeta.map(function (item) {
  return item.name;
});
