window.GUIDE_DATA = {
  cities: ["上海", "杭州", "北京"],
  weather: {
    上海: {
      day: "周六",
      sky: "多云",
      temp: 24,
      outdoorOk: true,
      text: "周六多云 24°C，适合户外",
      tip: "风力不大，滨江和市集体感舒适，记得带一件薄外套。"
    },
    杭州: {
      day: "周六",
      sky: "小雨",
      temp: 21,
      outdoorOk: false,
      text: "周六小雨 21°C，建议室内或备伞",
      tip: "西湖沿线会湿滑，展览和剧场更稳妥；若坚持徒步请穿防滑鞋。"
    },
    北京: {
      day: "周六",
      sky: "晴",
      temp: 26,
      outdoorOk: true,
      text: "周六晴 26°C，非常适合徒步与市集",
      tip: "紫外线偏强，户外活动建议防晒和补水。"
    }
  },
  activities: [
    {
      id: "sh-01",
      city: "上海",
      title: "西岸美术馆周末特展",
      category: "展览",
      cost: 80,
      duration: "2.5 小时",
      minPeople: 1,
      maxPeople: 6,
      meetup: "龙腾大道 2100 号西岸美术馆正门",
      indoor: true,
      time: "周六 13:30",
      vibe: "慢看",
      desc: "沿黄浦江的白盒子展厅，适合不想赶场、只想把一个展看完的下午。展后可步行去咖啡店复盘。"
    },
    {
      id: "sh-02",
      city: "上海",
      title: "武康路周末手作市集",
      category: "市集",
      cost: 40,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "武康路 393 号近安福路路口",
      indoor: false,
      time: "周六 11:00",
      vibe: "闲逛",
      desc: "梧桐树下的摊位以插画、银饰和咖啡为主，适合边走边聊，预算可控。"
    },
    {
      id: "sh-03",
      city: "上海",
      title: "上海交响乐团周末室内乐",
      category: "演出",
      cost: 180,
      duration: "1.5 小时",
      minPeople: 1,
      maxPeople: 4,
      meetup: "湖南路 105 号上海交响乐团音乐厅",
      indoor: true,
      time: "周六 19:30",
      vibe: "仪式感",
      desc: "夜场室内乐，时长适中，适合两三人把周末过得郑重一点。"
    },
    {
      id: "sh-04",
      city: "上海",
      title: "余山森林公园半日徒步",
      category: "徒步",
      cost: 0,
      duration: "4 小时",
      minPeople: 2,
      maxPeople: 10,
      meetup: "西佘山地铁站 2 号口",
      indoor: false,
      time: "周六 09:00",
      vibe: "出汗",
      desc: "上海最近的“像样山路”，爬升不陡，适合想离开市区又当天往返的小队。"
    },
    {
      id: "sh-05",
      city: "上海",
      title: "PSA 当代艺术博物馆",
      category: "展览",
      cost: 60,
      duration: "3 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "花园港路 201 号电厂烟囱下",
      indoor: true,
      time: "周六 14:00",
      vibe: "开阔",
      desc: "旧电厂改造的大空间，展线清楚，一个人或一群人都可以慢慢走完。"
    },
    {
      id: "sh-06",
      city: "上海",
      title: "思南公馆旧书与咖啡市集",
      category: "市集",
      cost: 30,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 6,
      meetup: "思南路 51-53 号花园入口",
      indoor: false,
      time: "周六 10:30",
      vibe: "安静",
      desc: "花园里翻旧书、喝手冲，适合不想太吵的周末上午。"
    },
    {
      id: "sh-07",
      city: "上海",
      title: "静安 livehouse 独立现场",
      category: "演出",
      cost: 120,
      duration: "2.5 小时",
      minPeople: 2,
      maxPeople: 6,
      meetup: "陕西北路近南京西路 livehouse 门口",
      indoor: true,
      time: "周六 20:00",
      vibe: "热闹",
      desc: "本地乐队周末专场，站票为主，适合想把晚上过得热闹一点的朋友。"
    },
    {
      id: "sh-08",
      city: "上海",
      title: "徐汇滨江黄昏漫步",
      category: "徒步",
      cost: 0,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "龙腾大道龙耀路路口滨江步道",
      indoor: false,
      time: "周六 16:30",
      vibe: "轻松",
      desc: "平坦步道看日落，几乎零花费，适合临时组队或约会收尾。"
    },
    {
      id: "sh-09",
      city: "上海",
      title: "朱家角水巷半日走逛",
      category: "徒步",
      cost: 50,
      duration: "5 小时",
      minPeople: 2,
      maxPeople: 8,
      meetup: "朱家角地铁站 1 号口",
      indoor: false,
      time: "周六 09:30",
      vibe: "短途",
      desc: "不出上海也能走到水乡，避开主街钻小巷会更舒服。"
    },
    {
      id: "sh-10",
      city: "上海",
      title: "外滩美术馆建筑展",
      category: "展览",
      cost: 50,
      duration: "1.5 小时",
      minPeople: 1,
      maxPeople: 5,
      meetup: "虎丘路 20 号外滩美术馆大堂",
      indoor: true,
      time: "周六 15:00",
      vibe: "短看",
      desc: "体量小、展线短，看完可以接着去外滩散步，适合时间被切碎的周末。"
    },
    {
      id: "hz-01",
      city: "杭州",
      title: "良渚博物院文明展",
      category: "展览",
      cost: 0,
      duration: "2.5 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "良渚博物院南门",
      indoor: true,
      time: "周六 13:00",
      vibe: "安静",
      desc: "免费预约制展览，雨天也舒适，适合想认真看展又不想花门票的组合。"
    },
    {
      id: "hz-02",
      city: "杭州",
      title: "西湖手作市集",
      category: "市集",
      cost: 40,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "湖滨步行街音乐喷泉附近",
      indoor: false,
      time: "周六 11:00",
      vibe: "热闹",
      desc: "湖边摊位以陶瓷、香薰和文创为主，适合边逛边吃。"
    },
    {
      id: "hz-03",
      city: "杭州",
      title: "运河大剧院周末剧场",
      category: "演出",
      cost: 160,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 4,
      meetup: "运河大剧院 3 号门",
      indoor: true,
      time: "周六 19:30",
      vibe: "仪式感",
      desc: "小剧场话剧，座位近、台词清楚，雨天首选。"
    },
    {
      id: "hz-04",
      city: "杭州",
      title: "九溪烟树林间徒步",
      category: "徒步",
      cost: 0,
      duration: "3.5 小时",
      minPeople: 2,
      maxPeople: 8,
      meetup: "九溪公交站林海亭",
      indoor: false,
      time: "周六 09:00",
      vibe: "出汗",
      desc: "溪声和湿石台阶是这条线的记忆点，小雨天需防滑，晴天则非常舒服。"
    },
    {
      id: "hz-05",
      city: "杭州",
      title: "南宋德寿宫遗址展",
      category: "展览",
      cost: 75,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 6,
      meetup: "德寿宫遗址博物馆检票口",
      indoor: true,
      time: "周六 14:30",
      vibe: "慢看",
      desc: "遗址和文物穿插，适合对杭州历史有一点好奇、又不想跑很远的人。"
    },
    {
      id: "hz-06",
      city: "杭州",
      title: "河坊街夜间市集",
      category: "市集",
      cost: 60,
      duration: "2.5 小时",
      minPeople: 2,
      maxPeople: 10,
      meetup: "河坊街与中山中路交叉口",
      indoor: false,
      time: "周六 18:00",
      vibe: "热闹",
      desc: "小吃和手作混在一起，适合人多、想把晚饭和闲逛并在一次完成。"
    },
    {
      id: "hz-07",
      city: "杭州",
      title: "西溪湿地绿道慢走",
      category: "徒步",
      cost: 80,
      duration: "3 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "西溪国家湿地公园周家村入口",
      indoor: false,
      time: "周六 09:30",
      vibe: "轻松",
      desc: "栈道平坦，适合不想爬山但想离开马路的组合。"
    },
    {
      id: "hz-08",
      city: "杭州",
      title: "云栖竹径半日走",
      category: "徒步",
      cost: 0,
      duration: "3 小时",
      minPeople: 2,
      maxPeople: 8,
      meetup: "云栖竹径石牌坊",
      indoor: false,
      time: "周六 08:30",
      vibe: "清爽",
      desc: "竹林夹道，夏季也阴凉。路面有青苔，雨天请换计划。"
    },
    {
      id: "hz-09",
      city: "杭州",
      title: "茶博周末特展",
      category: "展览",
      cost: 30,
      duration: "1.5 小时",
      minPeople: 1,
      maxPeople: 6,
      meetup: "中国茶叶博物馆双峰馆区",
      indoor: true,
      time: "周六 15:00",
      vibe: "短看",
      desc: "看完可以在茶室坐一会，适合想把周末过得慢一点的两三人。"
    },
    {
      id: "hz-10",
      city: "杭州",
      title: "大麦·杭州大剧院交响夜",
      category: "演出",
      cost: 220,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 4,
      meetup: "杭州大剧院歌剧院入口",
      indoor: true,
      time: "周六 19:30",
      vibe: "郑重",
      desc: "正厅观演体验完整，适合预算更宽、想给周末加一点仪式的人。"
    },
    {
      id: "bj-01",
      city: "北京",
      title: "国家博物馆周末特展",
      category: "展览",
      cost: 0,
      duration: "3 小时",
      minPeople: 1,
      maxPeople: 6,
      meetup: "国家博物馆西门安检口",
      indoor: true,
      time: "周六 13:00",
      vibe: "认真",
      desc: "预约免费，展线很长。建议只选一个特展，避免走成体力赛。"
    },
    {
      id: "bj-02",
      city: "北京",
      title: "798 周末创意市集",
      category: "市集",
      cost: 50,
      duration: "3 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "798 艺术区 2 号门",
      indoor: false,
      time: "周六 11:00",
      vibe: "闲逛",
      desc: "厂区里摊位和展览混着走，适合边拍照边找午饭。"
    },
    {
      id: "bj-03",
      city: "北京",
      title: "国图艺术中心室内乐",
      category: "演出",
      cost: 150,
      duration: "1.5 小时",
      minPeople: 1,
      maxPeople: 4,
      meetup: "国家图书馆艺术中心售票厅",
      indoor: true,
      time: "周六 19:30",
      vibe: "安静",
      desc: "厅不大、声音近，适合不想跑到大剧院又想听现场的人。"
    },
    {
      id: "bj-04",
      city: "北京",
      title: "奥林匹克森林公园南园徒步",
      category: "徒步",
      cost: 0,
      duration: "3 小时",
      minPeople: 1,
      maxPeople: 10,
      meetup: "奥森南园南门",
      indoor: false,
      time: "周六 08:30",
      vibe: "出汗",
      desc: "环湖加仰山，坡度温和，适合想在城里把腿走开的周末。"
    },
    {
      id: "bj-05",
      city: "北京",
      title: "今日美术馆当代展",
      category: "展览",
      cost: 60,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 6,
      meetup: "今日美术馆 1 号馆前台",
      indoor: true,
      time: "周六 14:00",
      vibe: "短看",
      desc: "体量适中，看完可以去附近吃一顿，适合下午档。"
    },
    {
      id: "bj-06",
      city: "北京",
      title: "五道营周末市集",
      category: "市集",
      cost: 40,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 6,
      meetup: "五道营胡同西口",
      indoor: false,
      time: "周六 12:00",
      vibe: "轻松",
      desc: "胡同尺度的摊位，适合人数不多、想聊天多于购物的组合。"
    },
    {
      id: "bj-07",
      city: "北京",
      title: "三里屯周末 livehouse",
      category: "演出",
      cost: 130,
      duration: "2.5 小时",
      minPeople: 2,
      maxPeople: 6,
      meetup: "工体北路 livehouse 门口",
      indoor: true,
      time: "周六 20:30",
      vibe: "热闹",
      desc: "夜场站票，适合想把周六晚上交给音乐的朋友。"
    },
    {
      id: "bj-08",
      city: "北京",
      title: "香山公园半日轻徒步",
      category: "徒步",
      cost: 10,
      duration: "4 小时",
      minPeople: 2,
      maxPeople: 8,
      meetup: "香山公园东门",
      indoor: false,
      time: "周六 08:00",
      vibe: "出汗",
      desc: "城里最经典的爬升之一。晴天视野好，记得防晒。"
    },
    {
      id: "bj-09",
      city: "北京",
      title: "中轴线漫步：天安门到正阳门",
      category: "徒步",
      cost: 0,
      duration: "2 小时",
      minPeople: 1,
      maxPeople: 8,
      meetup: "天安门东地铁站 C 口",
      indoor: false,
      time: "周六 16:00",
      vibe: "城市",
      desc: "短、平、好集合，适合第一次组队、先混个脸熟。"
    },
    {
      id: "bj-10",
      city: "北京",
      title: "园博园花田与展馆",
      category: "展览",
      cost: 0,
      duration: "3.5 小时",
      minPeople: 2,
      maxPeople: 10,
      meetup: "园博园东门",
      indoor: false,
      time: "周六 10:00",
      vibe: "开阔",
      desc: "户外观展和散步各占一半，天气好时非常值，雨天建议改室内。"
    }
  ]
};
